<?php

/**
 * Implementation of hook_menu.
 */
function islandora_pluploader_menu() {
  $items['islandora/pluploader/%'] = array(
    'title' => 'Upload Files',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_pluploader_form', 2),
    'access arguments' => array('islandora bulk upload files'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of hook_permission.
 */
function islandora_pluploader_permission() {
  return array(
    'islandora bulk upload files' => array(
      'title' => t('Bulk upload files'), 
      'description' => t('Bulk upload files for ingest with plupload.'),
    ),
  );
}

function islandora_pluploader_islandora_ingest_registry($collection_object) {
  module_load_include('inc', 'islandora', 'includes/islandora.ingest');
  $info = islandora_ingest_get_information($collection_object);
  
  $potential_models = array();
  if (!empty($info['models'])) {
    foreach ($info['models'] AS $model) {
      if ($model['pid'] == 'islandora:sp_basic_image') {
        $potential_models[] = $model['pid'];
      }
    }
  }
  
  if (count($potential_models > 0)) {
    return array(
      array(
        'name' => t('Islandora Bulk Upload'),
        'url' => 'islandora/pluploader/' . $collection_object->id,
        'weight' => 0
      ),
    );
  }
}

function islandora_pluploader_form($form, &$form_state, $collection_object_id) {
  $form = array();
  
  $form['pluploader'] = array(
    '#type' => 'plupload',
    '#title' => t('Files'),
  );
  
  $form['collection_object_id'] = array(
    '#type' => 'value',
    '#value' => $collection_object_id,
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Ingest'),
  );
  return $form;
}

function islandora_pluploader_form_validate($form, &$form_state) {
  
}

function islandora_pluploader_form_submit($form, &$form_state) {
  global $user;
  module_load_include('inc', 'islandora', 'includes/islandora.ingest');
  module_load_include('inc', 'islandora', 'includes/mime.detect');
  
  $collection_pid = $form_state['values']['collection_object_id'];
  
  $fedora_object = islandora_object_load($collection_pid);
  $collection_policy_info = islandora_ingest_get_information($fedora_object);
  $relationship = $collection_policy_info['relationship'];
  $content_models = array(array('pid' => 'islandora:sp_basic_image')); //@TODO: dynamic
  
  
  //@TODO: batch
  $i = 0;
  foreach ($form_state['values']['pluploader'] AS $file) {
    $i++;
    $real_path = drupal_realpath($file['tmppath']);
    $object = islandora_ingest_get_object($content_models, $collection_pid, $collection_policy_info['relationship'], 'islandora');
    
    $object->label = substr('Ingested image ' . $i, 0, 256); //@TODO: get from filename/metadata
    $object->owner = $user->name;
    $object->state = 'A';
    
    $ds = $object->constructDatastream('OBJ', 'M'); //@TODO: undo hardcode
    
    $ds->setContentFromFile($real_path);
    $ds->label = 'Image';
    //$mime_class = new MimeDetect();
    //$mime_type = $mime_class->getMimetype($real_path);
    $ds->mimetype = 'image/jpeg';  //@TODO: undo hardcode
    $object->ingestDatastream($ds);
    $object = islandora_ingest_add_object($object);
  }
  
  drupal_set_message(t('Images uploaded and ingested.'));
  $form_state['redirect'] = 'islandora/object/' . $collection_pid;
}